# ============================================================
#  SETUP: writes Code/Salmonparams.R and Code/MIPM_functions.R
#  directly to disk -- run this ONCE before run_pi_meeting_demo.R
#  This removes any need to manually upload/rename/place files.
# ============================================================

dir.create("Code", showWarnings = FALSE)

salmonparams_lines <- c(
"#Atlantic salmon parameters",
  "minmass<-0.03",
  "maxmass<-20000",
  "timescale = 1 #1 day",
  "spawningmonth = 11 #November",
  "spawningday = 1 #1st of the month",
  "#Data needed for fecundity function",
  "adult_mass_at_maturity = 1600 #g",
  "fecundity_lm_intercept = 7.260878",
  "fecundity_lm_slope = 1.012753",
  "mean_egg_size = 0.125",
  "egg_size_sd = 0.2",
  "#Data needed for growth",
  "#activation energy",
  "E=0.45",
  "#at0 varied",
  "MT_at0<- 0.0145767684333848 #Initial parameter estimate",
  "  ",
  "#Survival",
  "T_pk = 9.05793 #t peak",
  "power = 0.25 #quarter power",
  "E_D = 2.10602 #deactivation energy",
  "#z0 varied",
  "MT_z0<-0.00942460726973781 #Initial parameter estimate"
)
writeLines(salmonparams_lines, "Code/Salmonparams.R")

mipm_functions_lines <- c(
"#MIPM functions for changing at0 and z0 parameters",
  "",
  "#Source salmon parameters",
  "source(\"Code/Salmonparams.R\")",
  "",
  "#Global MIPM params",
  "# integration limits ",
  "min.size<- log(minmass) ",
  "max.size<- log(maxmass)",
  "# number of cells in the discretised kernel",
  "n=300 #can be changed ",
  "# boundary points (the edges of the cells defining the kernel)",
  "b= seq(min.size, max.size, length.out = n+1)",
  "# mesh points (midpoints of the cells)",
  "y=0.5*(b[1:n]+b[2:(n+1)])",
  "# width of the cells",
  "h=y[2]-y[1] #same as (log(max.size) - log(min.size))/n",
  "",
  "",
  "#######################################",
  "#Fecundity functions",
  "",
  "#Number of eggs",
  "f.yx <- function(xp, x, adult_mass = adult_mass_at_maturity, intercept = fecundity_lm_intercept, slope = fecundity_lm_slope){  #m: mass(g), intercept and slope: from number of eggs produced per mass ",
  "  x<-exp(x) ",
  "  xp<- exp(xp)",
  "  #create empty vector to populate",
  "  egg <- rep(0, length(x))",
  "  #sequence along mass to calculate number of eggs produced if over or equal to adult mass size",
  "  for (i in seq_along(x)){",
  "    if (x[i] >= adult_mass){",
  "      m <- x[i]/1000     #convert mass as fecundity relationship is in kg and mass is in g",
  "      egg_number <- exp(intercept)*(m^slope) ",
  "      female_egg_number<- egg_number/2 #divide egg number by two to account for 1:1 sex ratio to model females",
  "      egg[i]<- female_egg_number ",
  "    } else {",
  "      egg[i] <- 0",
  "    }",
  "  }",
  "  return(egg)",
  "}",
  "",
  "#Size dist of egg sizes: input in log space",
  "d.yx<- function(x, xp, mean_egg_size = mean_egg_size, egg_size_sd = egg_size_sd){ ",
  "  dnorm(x, mean = log(mean_egg_size), sd = egg_size_sd) ",
  "} ",
  "",
  "#######################################",
  "",
  "#Growth functions",
  "k = 8.62*(10^(-5)) # global parameter: boltzmann's constant",
  "",
  "#a. Development time from mass NEW",
  "development_time <- function(m, Tc, at0, E = E, m0 = minmass, M = maxmass){ #m: mass(g), Tc: temp degrees celsius, t0: normalisation constant, a: slope, alpha=-E/kT20",
  "  alpha = E/(k*(273^2))",
  "  t <-  log( (1-( (m0/M)^(0.25) ))/ ( 1- ((m/M)^(0.25)) ) ) * (4 * (M^0.25) / ( at0 * exp(alpha* ( Tc/(1+(Tc/273))) )) ) ",
  "  return(t)   #time in days to reach mass m",
  "}",
  "",
  "#b. Mass reached over developmental time NEW",
  "development_mass <- function(t, Tc, at0, E = E, m0 = minmass, M = maxmass){ #t: time in days from above function, Tc: temp degrees celsius, t0: normalisation constant, a: slope, alpha=-E/kT_0^2",
  "  k <- 8.62*(10^(-5))",
  "  alpha = E/(k*(273^2)) ",
  "  a_temp<- at0 * exp(alpha* (Tc/(1+(Tc/273))) )",
  "  m <- M * ( 1- (1-((m0/M)^0.25)) * (exp(-a_temp*t/(4*(M^0.25))) )) ^4",
  "  return(m) #mass reached after amount of time t",
  "}",
  "",
  "#c. size next",
  "sizeNext<-function(mass_vector, Tc, t, at0){ #Tc = temp degrees cels, t = time in days",
  "  # FIX: development_time()/development_mass() declare E = E as a default",
  "  # argument. In R this is self-referential and only resolves if E is passed",
  "  # explicitly (see explainer note). Passing it through here fixes the",
  "  # \"promise already under evaluation\" crash without changing behaviour.",
  "  time <- development_time(mass_vector, Tc, at0, E = E)  + t",
  "  mass_vector_next<- development_mass(time, Tc, at0, E = E)",
  "  return(mass_vector_next)",
  "}",
  "",
  "#The growth function with normal distr and sd, input in log space",
  "g.yx=function(x, xp, Tc , t, sd = h, at0) { ",
  "  #exponentiate masses ",
  "  mp<-exp(xp)",
  "  #sizeNext under Tc after t days",
  "  mass_t<-sizeNext(mp, Tc, t, at0)",
  "  #Log sizeNext ",
  "  log_mass_t<-log(mass_t)",
  "  #create normal distribution ",
  "  dnorm(x, mean = log_mass_t, sd =  sd) ",
  "}",
  "",
  "####################################",
  "#Survival Functions",
  "",
  "#U-shaped mortality",
  "Inv_sharpe_schoolfield_edited<- function(Tc, m, T_pk, z0, E, E_D, power){ #K is specified as global param for all other eqns",
  "  #Convert input temp to kelvin",
  "  Temp <- Tc+273.15 ",
  "  ",
  "  #Reference temp",
  "  T_ref<- 0+273.15 ",
  "  #T_pk has to be in kelvs too ",
  "  T_pk_kel<-T_pk+273.15",
  "  #Eqn",
  "  Inv_S_S<- ((z0) * m^ (-power))* (( ( ( ( - E * exp( (E_D*(Temp-T_pk_kel))/(Temp*T_pk_kel*k) )  + E - E_D)  )* exp( - (( E*(Temp-T_ref))/ (Temp * T_ref * k)) ) ) /  (  E-E_D )))  ",
  "  ",
  "  return(Inv_S_S)",
  "}",
  "",
  "s.x<- function(x, Tc, z0, E = E, T_pk = T_pk, power = power, E_D = E_D){",
  "  m<- exp(x) #exponentiate masses",
  "  #daily mortality rate",
  "  Z<-Inv_sharpe_schoolfield_edited(Tc, m, T_pk, z0, E, E_D, power)",
  "  #Convert to a daily survival probability",
  "  S_prob<- exp(-(Z)) #using exponential CDF",
  "  ",
  "  return(S_prob)",
  "} ",
  "",
  "",
  "",
  "######################################################################",
  "",
  "#CREATE MATRICES",
  "",
  "#Start with normal day daily P",
  "create_P_kernel<- function(y, h, Tc, t = timescale, at0 = at0, z0 = z0){ #specify min and max mass, n number of mesh points, exp-mesh = yes/no?",
  "  ",
  "  #Growth matrix G",
  "  G = h*outer(y, y, g.yx, Tc, t, at0 = at0)  ",
  "  # survival S",
  "  # FIX: s.x() declares E/T_pk/power/E_D as self-referential defaults;",
  "  # pass them through explicitly (see explainer note).",
  "  S = s.x(y, Tc, z0 = z0, E = E, T_pk = T_pk, power = power, E_D = E_D)",
  "  # P matrix:",
  "  P = G       ",
  "  for(i in 1:n) P[,i]=G[,i]*S[i]  ",
  "  ",
  "  return(P)",
  "}",
  "",
  "create_P_month<- function(y, h, month, Temp_vector, leapyear, at0 = at0, z0 = z0){  # month as a number e.g. Jan = 1, Feb = 2... etc, Tempvector data has be of year length and start from julian day 1 (01/01/YYYY)",
  "  #The Julian day at the beginning of each month ",
  "  if (leapyear == \"yes\"){",
  "    jday =  c(1,  32,  61,  92, 122, 153, 183, 214, 245, 275, 306, 336, 366)",
  "  }else if (leapyear == \"no\") {",
  "    jday =  c(1,  32,  60,  91, 121, 152, 182, 213, 244, 274, 305, 335, 365)",
  "  } else (stop(\"check leapyear\"))",
  "  ",
  "  #Temperature vector depending on ",
  "  if (month == 12){",
  "    month_temps<- Temp_vector[(jday[month]):(jday[month+1])] #the final day in the vector",
  "  }else  {",
  "    month_temps<- Temp_vector[(jday[month]):(jday[month+1]-1)]",
  "  }",
  "  ",
  "  #Create survival matrices",
  "  P_day <- vector(\"list\",length(month_temps))",
  "  for (i in seq_along(month_temps)){",
  "    P_day[[i]]<- create_P_kernel (y, h, Tc = month_temps[i], at0 = at0, z0 = z0)",
  "  }",
  "  ",
  "  #Use Reduce function reduce to multiply all elements",
  "  month_matrix<-Reduce(\"%*%\", P_day)",
  "  ",
  "  return(month_matrix)",
  "}",
  "",
  "",
  "",
  "#Reproduction day K = P+R",
  "create_K_kernel<- function(y, h, Tc, t = timescale, at0 = at0, z0 = z0){ #specify min and max mass, n number of mesh points, exp-mesh = yes/no?",
  "  ",
  "  #Growth matrix",
  "  G = h*outer(y,y,g.yx, Tc, t, at0 = at0)  ",
  "  # survival ",
  "  # FIX: same s.x() self-referential default issue as in create_P_kernel()",
  "  S = s.x(y, Tc = Tc, z0 = z0, E = E, T_pk = T_pk, power = power, E_D = E_D)",
  "  #these give us our P matrix:",
  "  P = G          ",
  "  for(i in 1:n) P[,i]=G[,i]*S[i]  ",
  "  #Fecundity matrix",
  "  F=outer(y, y, f.yx)   # reproduction kernel",
  "  #Eggs",
  "  # FIX: d.yx() declares mean_egg_size/egg_size_sd as self-referential",
  "  # defaults; pass them through explicitly (see explainer note).",
  "  D = h*outer(y,y,d.yx, mean_egg_size = mean_egg_size, egg_size_sd = egg_size_sd)",
  "  #Number and size of eggs",
  "  R= F*D",
  "  #the whole kernel",
  "  K = P+R ",
  "  return(K)",
  "}",
  "",
  "",
  "#fecundity on one day of the month, later specified as 1st day here",
  "create_K_month<- function(y, h, Temp_vector, leapyear, month, spawningday, at0 = at0, z0 = z0){  # month as a number e.g. Jan = 1, Feb = 2... etc, Tempvector data has be of year length and start from julian day 1 (01/01/YYY)",
  "  #The Julian day at the beginning of each month ",
  "  if (leapyear == \"yes\"){",
  "    jday =  c(1,  32,  61,  92, 122, 153, 183, 214, 245, 275, 306, 336, 366)",
  "  }else if (leapyear == \"no\") {",
  "    jday =  c(1,  32,  60,  91, 121, 152, 182, 213, 244, 274, 305, 335, 365)",
  "  } else (stop(\"check leapyear\"))",
  "  ",
  "  #Temperature vector depending on ",
  "  if (month == 12){",
  "    month_temps<- Temp_vector[(jday[month]):(jday[month+1])] #the final day in the vector",
  "  }else  {",
  "    month_temps<- Temp_vector[(jday[month]):(jday[month+1]-1)]",
  "  }",
  "  ",
  "  #Create survival matrices",
  "  P_day <- vector(\"list\",length(month_temps))",
  "  for (i in seq_along(month_temps)){",
  "    P_day[[i]]<- create_P_kernel(y, h, Tc = month_temps[i], at0 = at0, z0 = z0)",
  "  }",
  "  ",
  "  #Spawning day",
  "  spawning_day_temp<-Temp_vector[(jday[month]+spawningday-1)]",
  "  K_day<- create_K_kernel(y, h, Tc = spawning_day_temp, at0 = at0, z0 = z0)",
  "  ",
  "  #Replace P matrix in P_day with K matrix created",
  "  P_day[[spawningday]]<- K_day",
  "  ",
  "  #Use Reduce function reduce to multiply all elements",
  "  month_matrix<-Reduce(\"%*%\", P_day)",
  "  ",
  "  return(month_matrix)",
  "}",
  "",
  "###### a modification from projectmonthmatrices",
  "#Create month matrices",
  "get_month_matrices<- function (y, h, n, Temp_vector_data, spawningmonth = spawningmonth, spawningday = spawningday, at0 = at0, z0 = z0){",
  "  ",
  "  start_time<-Sys.time()",
  "  ",
  "  years<- unique(Temp_vector_data$no.years.for.sim)",
  "  ",
  "  #create vector to put all months into",
  "  allmonths<-vector(\"list\", max(years))",
  "  ",
  "  #time frame beginning with spawning month",
  "  if (spawningmonth==1){",
  "    time <- 1:12",
  "  } else if (spawningmonth %in% 2:12) {",
  "    time<- c(spawningmonth:12,1:(spawningmonth-1))",
  "  }",
  "  ",
  "  #leap year?",
  "  for (i in seq_along(years)){",
  "    ",
  "    data2subset<-subset(Temp_vector_data, no.years.for.sim == i) #novyears",
  "    Temp_vector<- data2subset$meantemp #Temp_vector_data needs to have meantemp column",
  "    ",
  "    if (nrow(data2subset) == 366){",
  "      leapyear <- \"yes\"",
  "    } else if (nrow(data2subset) == 365){",
  "      leapyear <- \"no\"",
  "    } else {",
  "      stop(\"wrong number of days\")",
  "    }",
  "    ",
  "    #create months list",
  "    months<- list()",
  "    ",
  "    #spawning month as first month",
  "    months[[1]] <-create_K_month(y, h, Temp_vector = Temp_vector, leapyear = leapyear, month = spawningmonth, spawningday = spawningday, at0 = at0, z0 = z0)",
  "    #rest of months",
  "    for (j in 2:12){",
  "      months[[j]] <- create_P_month(y, h, month = time[j] , Temp_vector = Temp_vector, leapyear = leapyear, at0 = at0, z0 = z0)",
  "    }",
  "    ",
  "    #months into a year",
  "    allmonths[[i]]<- months",
  "    ",
  "  }",
  "  ",
  "  #Un list allmonths to loop over",
  "  allmonths<-lapply(rapply(allmonths, enquote, how=\"unlist\"), eval)",
  "  ",
  "  #How long function takes to run",
  "  end_time<- Sys.time()",
  "  print(end_time - start_time)",
  "  ",
  "  return(allmonths) ",
  "}",
  "",
  "#Calculate lambda from month matrices",
  "get_lambda<- function(allmonths){",
  "  #Combine matrices into one",
  "  years_lambda<- Reduce(\"%*%\", allmonths)",
  "  #Calculate lambda",
  "  lambda<-(lam=Re(eigen(years_lambda)$values[1])) ",
  "  return(lambda)",
  "}",
  "",
  "################################################################################",
  "#Functions needed for running manuscript code",
  "",
  "#Create function to make fixed temp dataframe (fixed for 70 years for now)",
  "create_fixed_temp_df<- function(fixdtemp, n_yrs = 70){",
  "  meantemp<-  rep(fixdtemp,365*n_yrs) ",
  "  fixed_temp_data<-as.data.frame(meantemp)",
  "  fixed_temp_data$no.years.for.sim<-rep(1:n_yrs, each = 365)",
  "  return(fixed_temp_data)",
  "}",
  "",
  "#remove 40 years (480 months) burn in time",
  "burnin2remove<-1:(40*12)"
)
writeLines(mipm_functions_lines, "Code/MIPM_functions.R")

cat("Setup complete. Files written:\n")
print(list.files("Code"))
